import React from "react";
import "./App.css";
import BillingEntry from "./Components/BillingEntry/BillingEntry";
import Invoice from "./Components/Invoice/Invoice";
import { BrowserRouter as Router, Link, Routes, Route } from "react-router-dom";
const App = () => {
  //addresses
  const addresses = [
    "ADITYA ENGINEERS	PRASHANTHI NAGAR	KUKATPALLY,HYDERABAD,	GSTIN : 36AAOFA2372F1Z1",
    "ANJANA ENGG WORKS	RC PURAM	HYDERABAD,GSTIN : 36AEWPB6015N3Z1	",
    "ASHOKA ROAD EQUIPMENT AND MFC. PVT. LTD.		HYDERABAD.	,GSTIN : 36AANCA0669D1ZP	",
    "B. S. TECHNOLOGIES	PRASHANTHNAGAR,KUKATPALLY	HYDERABAD.	,GSTIN : 36BQZPB6230M1ZB",
    "BEMC INDUSTRIES PVT LTD	PRASHANTHNAGAR, KUKATPALLY	HYDERABAD.	,GSTIN : 	",
    "DECCAN ISPAT UDYOG	FATHENAGAR	HYDERABAD	,GSTIN : 36AAYPA92501ZI",
    "DELTA SERVICE ENGINEERS	PRASHANTH NAGAR	HYDERABAD.	,GSTIN : 36ADTPA7882N1ZO	",
    "FLUID POWER ENGINEERING	PRASHANTHI NAGAR	KUKATPALLY,HYDERABAD	,GSTIN : 36AAFPT3280Q1ZZ",
    "FLUID POWER SYSTEMS	PRASHANTHNAGAR,KUKATPALLY	HYDERABAD.	,GSTIN : 36AJSPK6669E2ZL",
    "GANESH LAB EQUIPMENTS	PRASHANTH NAGAR, KUKATPALLY	HYDERABAD	,GSTIN : 36ALOPG1331R1ZQ",
    "GERMANE TOOLS & TECHNOLOGIES	RAJIV GANDHI NAGAR, KUKATPALLY	HYDERABAD	,GSTIN : 36ALGPK2989P1Z8:",
    "GSM TECHNOLOGIES	PRASHANTH NAGAR, KUKATPALLY	HYDERABAD	,GSTIN :",
    "HYDROPNEU HYDROLIS INDIA PVT LTD.	SRIPURAM COLONY, CHENGICHERLA	HYDERABAD.	,GSTIN : 36AADCH2275G1ZO	",
    "JAHANAVI CNC TECHNICS	PRASHANTHI NAGAR	KUKATPALLY,HYDERABAD	,GSTIN : 36AJPPD3362E1ZC	",
    "KEERTHI AGRO INDUSTRIES	PRASHANTHNAGAR,KUKATPALLY	HYDERABAD.	,GSTIN : 36ZMPN4376R1ZA",
    "KHAITHAN STEEL TRADERS	PLOT NO. 5&6, SATELITE INDUSTRIAL ESTATE	BALANAGAR,HYDERABAD.	,GSTIN : 36AGJPK6259J1ZX	",
    "KLICHAKRA MACHINARY PVT LTD	CHERIYALA	MEDAK DST	,GSTIN : 36AAGCK8155M1ZY	",
    "KRISHNA BHANU INDUSTRIES	BALNAGAR	HYDERABAD	,GSTIN : 36AMGPG6907N1ZO",
    "LAKSHMI VENKATESHWARA INDUSTRIES	PRASANTHI NAGAR	KUKATPALLY,HYDERABAD	,GSTIN : 36CIGPAO0361Q1Z	",
    "M M ENGINEERING WORKS	SHOBANA COLONY	HYDERABAD.	,GSTIN : 36ADCPV3976M1Z2	",
    "M R LABMART	PRASHANTH NAGAR, KUKATPALLY	HYDERABAD.	,GSTIN : 36AZVPK1870C1Z6",
    "MANIKANTA ENGINEERING WORKS	PANCHASHEELA COLONY, GANDHINAGART	RANGA REDDY, 500037	,GSTIN : 36ACVPV6345A1Z6	",
    "MGS MACHINE TOOLS	BALANAGAR,HYDERABAD	KUKATPALLY,HYDERABAD	,GSTIN : 36ABHFM9856C1ZY",
    "MICPRO	PRASHANTH NAGAR, KUKATPALLY	HYDERABAD	,GSTIN : 36AADCM9453H1Z9",
    "NARMADA CHEMICALS INDISTRS	PRASHANTHI NAGAR	KUKATPALLY,HYDERABAD	,GSTIN : 36AFHPT3764N1ZO",
    "NRC AEROSPACE INDIA PVT LTD	PRASANTHI NAGAR	KUKATPALLY,HYDERABAD	,GSTIN : 36AAFCN1035N2ZC",
    "PAVAN ELECTRICALS	PRASHANTHI NAGAR	KUKATPALLY,HYDERABAD	,GSTIN : 36AGYPD0247N1ZX",
    "PAVANI ENGINEERING WORKS	PRASHANTH NAGAR., KUKATPALLY	HYDERABAD.	,GSTIN : 36APPPM6632L1ZP",
    "PHYSEMECH INSTRUMENTS	B-12, BHEL  ANCILARY	ASHOK NAGAR	,GSTIN : 36AACCP1040J1ZP",
    "POOJA ENGINEERING INDUSTRIES	SHAKTHIPURAM, PRASHANT NAGAR	HYDERABAD.	,GSTIN : 36AAIFP3520A1ZR",
    "PRASAD ENGINEERING WORKS	THE CO-OPP INDUSTRIAL ESTATE	BALANAGAR,HYDERABAD.	,GSTIN : 36ALAPS3899J1ZF",
    "RAJESH ENGG WORKS			,GSTIN : 36AAFPY8863Q1ZF",
    "RAKESH MACHINE TOOLS	PLOT NO.6A/8,PHASE-1,IDA	PATANCHERU,SANGAREDDY,TELANGANA	,GSTIN : ",
    "RELIANCE ENGINEERING	KPHB AKRUTHI ENCLAVE	HYDERABAD.	,GSTIN : 36AGVPD7136M1ZS",
    "S&U MEK ENGINEERS PVT. LTD.	27,IDA,BALANAGAR	HYDERABAD-500037	,GSTIN : 36AAGSC8513B1ZJ",
    "SHIV STEEL TRADERS	FATENAGAR MAIN ROAD	HYDERABAD 500018	,GSTIN : 36ABVPD6675J1ZY",
    "SKYLINE CRANES AND HOISTS	MADHURANAGAER, SR NAGAR	HYDERABAD.	,GSTIN : 36AHQPK4249J1ZU",
    "SMRJ INDUSTRIES PVT LTD	PRASHANTHI NAGAR	KUKATPALLY,HYDERABAD	,GSTIN : 36AAGC50888P1ZK	",
    "SRAVANA HYDRAULICS	PANCHASHEELA COLONY, BALANAGAR	HYDERABAD.	,GSTIN : 36AGVPD7136M1ZS",
    "SRI SAI MANOHAR ENGG WORKS	PRASHANTHNAGAR,KUKATPALLY	HYDERABAD.	,GSTIN : 36AGUPA4255H1Z9",
    "SRI SAI TEJA ENGINEERING WORKS	RAMACHANDRAPURAM	HYDERABAD.	,GSTIN : 36ABBFS4039B1ZJ",
    "SRI SAI TOOLS	SHAKTHIPURAM,PRASHANTH NAGAR	KUKATPALLY,HYDERABAD	,GSTIN : 36DBKPK5990R1ZJ",
    "SRI VINAY EXPORTS	KURNOOL RD, BUDAVADA	PRAKASAM DT.	,GSTIN : 37ACYFS8342R1ZP",
    "SRI VINAY PRECISION TECHNICS	PRASHANTH NAGAR	HYDERABAD.	,GSTIN : 36AAOFS6769E1ZL",
    "STAY ON PAPERS PVT LTD	APPAREL EXPORT PARK, GUNDLAPOCHAMPALI	HYDERABAD.	,GSTIN : 36AADCS4122M1ZA",
    "SV ENGG INDUSTRIES	PRASHANTH NAGAR, KUKATPALLY	HYDERABAD	,GSTIN : 36CIHPS4990N1ZA",
    "TRISHATI ENGINEERING INDUSTRIES	PATANCHERU 	MEDAK DIST	,GSTIN : 36AQXPK7014K1Z9",
    "TRITON PRECISION DRIVES	PRASHANTH NAGAR, KUKATPALLY	HYDERABAD.	GSTIN : 36AADFJ7363D1Z6	",
    "UNITED ENGINEERING WORKS	PRASHANTHNAGAR,KUKATPALLY	HYDERABAD.	,GSTIN : 36AFRPM4307C1ZJ	",
    "VSP INDUSTRIES	PRASHANTH NAGAR,KUKATPALLY	HYDERABAD	,GSTIN : 36AADFV10901C1ZP",
  ];
  //materials
  const materials = [
    {
      material: "EN 8",
      hsnNo: "7214",
    },
    {
      material: "EN 1ALEADED",
      hsnNo: "7228",
    },
    {
      material: "EN19",
      hsnNo: "7224",
    },
    {
      material: "MS",
      hsnNo: "7214",
    },
    {
      material: "MS BRIGHT",
      hsnNo: "7214",
    },
  ];
  //materialIcons
  const materialIcons = ["∅", "▢"];
  return (
    <div>
      <Router>
        <Routes>
          <Route
            path="/"
            exact
            element={
              <BillingEntry
                addresses={addresses}
                materialIcons={materialIcons}
                materials={materials}
              />
            }
          />
          <Route path="invoice" exact element={<Invoice />} />
        </Routes>
      </Router>
    </div>
  );
};

export default App;
